### PR TITLE
Title tag added for report and unreport status

### PR DESCRIPTION
**Pull request by espellcaste**
More information here: https://github.com/jjeaton/bbpress-report-content/issues/9

### CODE REVIEW

**Comment by jjeaton** [comment]
Can you explain the purpose of this? It looks like the title is still the same for both topics and replies, it's just been moved to a variable.

**Comment by espellcaste** [comment]
Let me explain.

Consider these two situations:

The user is going to report a topic or reply, in this case, the topic/reply status is no reported. So when you hover the report link, the title appears the same for both status.

If the topic is already reported, but you want unreport, when you hover the unreport link, currently the title show "Report inapropriate content", when it should be "Unreport inapropriate content".

Got it?! I understand this is might be trivial, it was something I thought it was important in my community and decided to share it with you. =)

**Comment by espellcaste** [comment]
Simply, if the topic is unreported, it is gonna show the "Report title", if it reported, it's gonna show the "Unreport title".

**Comment by jjeaton** [comment]
Ah! Sorry, I was confused. I see what you mean now. Thanks very much for the PR!

**Comment by espellcaste** [comment]
=)

**Pull request merged**
